import type { Metadata } from "next";
import { ClientClock } from "./ClientClock";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ConfigLayout() {
  const renderTime = new Date().toLocaleDateString("en", {
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
    hour12: false,
  });

  return (
    <>
      <header>
        <h1>Test Page</h1>
      </header>
      <main>
        <h2>{`Last Time Rendered On Server`}</h2>
        <h3>{renderTime}</h3>
        <ClientClock />
      </main>
      <footer>Footer</footer>
    </>
  );
}
